[phases.setup]
nixPkgs = ["python3", "nodejs-18", "pnpm", "ffmpeg"]

[phases.install]
cmds = [
  "ln -s /usr/bin/python3 /usr/bin/python || true",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]